config/routes.rb
Rails.application.routes.draw do
  
  root to: "welcome#index"
  
  get 'welcome/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  get 'calendar_actions/all', to: 'calendar_actions#all'

  resources :calendar_actions


end

app/models/action.rb
class Action < ActiveRecord::Base
	belongs_to: user
	
end

app/models/calendar_action.rb
class CalendarAction < ActiveRecord::Base
	belongs_to :user

	validates :title, presence: true, length: { minimum: 5}
	validates :start_date, presence: true
	validates :end_date, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :actions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2, :twitter, :github]

def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.create(
           email: data["email"],
           password: Devise.friendly_token[0,20]
        )
    end
    
    user
end

def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.uid + "@twitter.com").first
      if registered_user
        return registered_user
      else

        user = User.create(
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.uid+"@twitter.com",
                            password:Devise.friendly_token[0,20],
                          )
      end

    end
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calendar_actions_controller.rb
class CalendarActionsController < ApplicationController
	before_action :authenticate_user!

	def index
		@calendar_actions = CalendarAction.all
	end

	def all
		@calendar_actions = CalendarAction.all
	end

	def show
		@calendar_action = CalendarAction.find(params[:id])
	end

	def new
		@calendar_action = CalendarAction.new
	end

	def edit
		@calendar_action = CalendarAction.find(params[:id])
	end

	def create
		@calendar_action = CalendarAction.new(calendar_action_params)
 
  		if @calendar_action.save
  			redirect_to @calendar_action
  		else
  			render 'new'
		end
	end

	def update
		@calendar_action = CalendarAction.find(params[:id])

		if @calendar_action.update(calendar_action_params)
			redirect_to @calendar_action
		else
			render 'edit'
		end
	end

	def destroy
		@calendar_action = CalendarAction.find(params[:id])
		@calendar_action.destroy

		redirect_to calendar_actions_path
	end

	private

		def calendar_action_params
			params.require(:calendar_action).permit(:title, :description, :start_date, :end_date)
		end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def google_oauth2
	      @user = User.from_omniauth(request.env["omniauth.auth"])

	      if @user.persisted?
	        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
	        sign_in_and_redirect @user, :event => :authentication
	      else
	        session["devise.google_data"] = request.env["omniauth.auth"]
	        redirect_to new_user_registration_url
	      end
  	end

  	def twitter
	    auth = env["omniauth.auth"]

	    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"],current_user)
	    
	    if @user.persisted?
	      flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
	      sign_in_and_redirect @user, :event => :authentication
	    else
	      session["devise.twitter_uid"] = request.env["omniauth.auth"]
	      redirect_to new_user_registration_url
	    end
  	end

  	def github
  		@user = User.from_omniauth(request.env["omniauth.auth"])

  		if @user.persisted?
  			flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
  			sign_in_and_redirect @user, :event => :authentication
  		else
  			session["devise.github_data"] = request.env["omniauth.auth"]
  			redirect_to new_user_registration_url
  		end
  	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	redirect_to calendar_actions_path if user_signed_in? 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def has_image_login(provider)
		providers = [:google_oauth2, :twitter, :github]
		providers.each do |registered|
			if registered == provider
				return true
			end
		end
		false
	end

	def login_image(provider)
		if provider == :google_oauth2
			return "google_button"
		elsif provider == :twitter
			return "twitter_logo"
		elsif provider == :github
			return "github_logo"
		end
	end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/calendar_actions/all.html.erb
<div class="row">
	<%= render 'calendar_actions/partials/dropdown_menu'%>
	<div class="col-md-8">
		<h1 class="text-center">All Calendar Actions</h1>
	</div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
      <table class="table table-condensed">
        <thead>
            <tr>
                <th id="title">Title</th>
                <th id="description-header">Description</th> 
                <th id="date">Start Date</th>
                <th id="date">End Date</th>
                <th id="action"></th>
            </tr>
        </thead>
    </table>
</div>
<div class="panel-body">
    <table class="table table-condensed table-hover">
        <tbody>
        	<% @calendar_actions.each do |calendar_action| %>
            <tr>
                <td id="title">
                <%= link_to calendar_action.title, calendar_action_path(calendar_action) %>
                </td>
                <% if calendar_action.description %>
                	<td id="description"><%= calendar_action.description %></td>
                <% else %>
                	<td id="description"> No description </td>
                <% end %>
                <td id="date"><%= calendar_action.start_date %></td> 
                <td id="date"><%= calendar_action.end_date %></td> 
                <td id="action">
                	<%= link_to calendar_action_path(calendar_action), title: "View", class: 'btn btn-success' do%>
                		<span class="glyphicon glyphicon-eye-open"></span>
                	<% end %>
                	<%= link_to edit_calendar_action_path(calendar_action), title: "Edit", class: 'btn btn-info' do%>
                		<span class="glyphicon glyphicon-pencil"></span>
                	<% end %>
                	<%= link_to calendar_action_path(calendar_action),
                		title: "Delete",
                	 	class: 'btn btn-danger',
                	 	method: :delete,
                	 	data: { confirm: 'Are you sure?' } do %>
                		<span class="glyphicon glyphicon-remove"></span>
                	<% end %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>
</div>

app/views/calendar_actions/edit.html.erb
<h1 class="text-center"> Editing Calendar Action</h1>

<%= render 'calendar_actions/partials/form' %>

app/views/calendar_actions/index.html.erb
<div class="row">
	<%= render 'calendar_actions/partials/dropdown_menu'%>
	<div class="col-md-8">
		<h1 class="text-center">Calendar</h1>
	</div>
</div>

<%= content_tag 'div', id: "calendar", data: {actions: @calendar_actions} do %>
<% end %>

<%= javascript_include_tag "display_calendar" %>

app/views/calendar_actions/new.html.erb
<h1 class="text-center">New Calendar Action</h1>

<%= render 'calendar_actions/partials/form' %>

app/views/calendar_actions/partials/_dropdown_menu.html.erb
<div class="col-md-2">
    <div class="btn-group">
  <button type="button" class="btn btn-primary">View</button>
  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu">
    <li>
    <%= link_to "Calendar View", calendar_actions_path %>
    </li>
    <li>
    <%= link_to "All Calendar Actions View", calendar_actions_all_path %>
    </li>
    <li role="separator" class="divider"></li>
    <li>
    <%= link_to "Create a New Calendar Action", new_calendar_action_path %>
    </li>
  </ul>
</div>
</div>

app/views/calendar_actions/partials/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for @calendar_action do |f| %>

    <% if @calendar_action.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@calendar_action.errors.count, "error") %> prohibited
          this calendar_action from being saved:
        </h2>
        <ul>
          <% @calendar_action.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <div class="form-group">
        <%= f.label :title %>:
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description %>:
        <%= f.text_area :description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :start_date %>:
        <%= f.datetime_select :start_date, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :end_date %>:
        <%= f.datetime_select :end_date, class: 'form-control' %>
      </div>
        <%= f.submit class: 'btn btn-success' %>
        <%= link_to 'Back', calendar_actions_path, class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/calendar_actions/show.html.erb
<h1 class="text-center">Calendar Action Details</h1>

<h3>Title: <%= @calendar_action.title %></h3>
<ul class="list-group">
	<li class="list-group-item">
		<strong>Description:</strong> <%= @calendar_action.description %>
	</li>
	<li class="list-group-item">
		<strong>Start date:</strong>
  		<%= @calendar_action.start_date %>	
	</li>
	<li class="list-group-item">
		<strong>End date:</strong>
  		<%= @calendar_action.end_date %>
	</li>
</ul>
<div class="row">	
<%= link_to 'Edit', edit_calendar_action_path(@calendar_action), class: 'btn btn-success' %>
<%= link_to 'Destroy', calendar_action_path(@calendar_action),
			  class: 'btn btn-danger',
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', calendar_actions_path, class: 'btn btn-default' %> 
</div>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-default navbar-fixed-bottom">
	<div class="container">
	<p id="footer">&copy; Company 2015</p>
	</div>
</footer>

app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-fixed-top navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Calendar App', root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active">
        <%= link_to 'Home', root_path%>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
        <li class="active"><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign up!', new_user_registration_path %></li>
        <% else %>
        <li><%= link_to "New Calendar Action", new_calendar_action_path %></li>
        <li class="active"><%= link_to 'Sign out', destroy_user_session_path, method: :delete  %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>CalendarToDoApp</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navbar' %>
	<div class="container">
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>	
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
	<h1>Calendar To Do App</h1>
	<p>This is a simple app that allows you to store task call appointments in a calendar. You will be allow to create, edit and assign these appointments to any user registered.</p>
	<p>
		<%= link_to 'Go to App >>', calendar_actions_path, class: "btn btn-lg btn-primary" %>
	</p>
</div>